base_images:
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: ci/containerimages/fetch-managed-clusters/Dockerfile
  to: fetch-managed-clusters-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: test-image
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    test:
    - ref: acm-fetch-managed-clusters
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: acmqe-autotest
  variant: debug_base_image
