base_images:
  acmqe-grc-test:
    name: "2.9"
    namespace: acm-qe
    tag: acmqe-grc-test
  application-ui-test:
    name: "2.9"
    namespace: acm-qe
    tag: application-ui-test
  clc-ui-e2e:
    name: "2.9"
    namespace: acm-qe
    tag: clc-ui-e2e
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  fetch-managed-clusters:
    name: autotest
    namespace: acm-qe
    tag: fetch-managed-clusters
  observability-core-automation:
    name: "2.9"
    namespace: acm-qe
    tag: observability-core-automation
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: acm-interop-aws
  cron: 0 6 25 12 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      SLEEP_DURATION: 1m
    test:
    - ref: wait
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: acmqe-autotest
  variant: acm-ocp4.14-lp-interop
