base_images:
  acmqe-grc-test-2.8:
    name: "2.8"
    namespace: acm-qe
    tag: acmqe-grc-test
  acmqe-grc-test-2.9:
    name: "2.9"
    namespace: acm-qe
    tag: acmqe-grc-test
  application-ui-test-2.8:
    name: "2.8"
    namespace: acm-qe
    tag: application-ui-test
  application-ui-test-2.9:
    name: "2.9"
    namespace: acm-qe
    tag: application-ui-test
  clc-ui-e2e-2.8:
    name: "2.8"
    namespace: acm-qe
    tag: clc-ui-e2e
  clc-ui-e2e-2.9:
    name: "2.9"
    namespace: acm-qe
    tag: clc-ui-e2e
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
  fetch-managed-clusters:
    name: autotest
    namespace: acm-qe
    tag: fetch-managed-clusters
  observability-core-automation-2.8:
    name: "2.8"
    namespace: acm-qe
    tag: observability-core-automation
  observability-core-automation-2.9:
    name: "2.9"
    namespace: acm-qe
    tag: observability-core-automation
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- dockerfile_literal: |
    FROM src
  from: src
  inputs:
    clc-ui-e2e-2.8:
      paths:
      - destination_dir: .
        source_path: /tmp/clc
    clc-ui-e2e-2.9:
      paths:
      - destination_dir: .
        source_path: /tmp/clc
  to: clc-ui-e2e-new
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: acm-interop-aws
  cron: 0 6 25 10 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      SLEEP_DURATION: 1h
    test:
    - ref: wait
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: acmqe-autotest
  variant: acm-ocp4.15-lp-interop-dynamic-image-testing
