base_images:
  clc-ui-e2e:
    name: "2.7"
    namespace: acm-qe
    tag: clc-ui-e2e
  cli:
    name: "4.11"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_literal: |
    FROM this-is-ignored
    RUN dnf install -y git
  from: cli
  to: cli-with-git
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.11"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: opp-interop-aws
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      COMPUTE_NODE_TYPE: m6a.2xlarge
      OPERATORS: |
        [
          {"name": "advanced-cluster-management", "source": "redhat-operators", "channel": "release-2.7", "install_namespace": "ocm", "target_namespaces": "ocm"}
        ]
      ZONES_COUNT: "4"
    test:
    - ref: install-operators
    - ref: acm-mch
    - ref: acm-policies-openshift-plus-setup
    - ref: acm-policies-openshift-plus
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: policy-collection
  variant: opp-ocp4.11-interop
