base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  rhtap-installer:
    name: redhat-appstudio
    namespace: ci
    tag: rhtap-installer
build_root:
  project_image:
    dockerfile_path: ci/Dockerfile
images:
- dockerfile_path: ci/Dockerfile
  from: src
  to: rhtap-cli
- dockerfile_literal: |
    FROM src
    COPY oc /usr/bin/oc
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: src-oc
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.15"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: rhtap-cli-install-nightly
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhtap
    product: ocp
    timeout: 1h0m0s
    version: "4.15"
  cron: 0 */24 * * *
  steps:
    workflow: redhat-appstudio-rhtap-cli
- as: rhtap-cli-gitops-prerelease
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhtap
    product: ocp
    timeout: 1h0m0s
    version: "4.15"
  cron: 0 0 30 6 *
  steps:
    workflow: redhat-appstudio-rhtap-cli-gitops-prerelease
zz_generated_metadata:
  branch: main
  org: redhat-appstudio
  repo: rhtap-cli
