base_images:
  cli:
    name: "4.11"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.15
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.11"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.11"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: acceptance
  steps:
    test:
    - as: test-command-env-var
      cli: latest
      commands: |
        echo $CLONEREFS_OPTIONS
        ls
      from: src
      resources:
        requests:
          cpu: 100m
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: playground-rehearse
