base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: test-interop-aws
  cron: 0 6 25 12 *
  steps:
    cluster_profile: aws-cspi-qe
    test:
    - ref: wait
zz_generated_metadata:
  branch: master
  org: rhpit
  repo: interop-tests
  variant: ocp4.14.z-lp-interop
