base_images:
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: jws-interop-aws
  cron: 0 6 25 12 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      FIREWATCH_CONFIG: "{\n  \"failure_rules\":\n    [\n    ]\n}  \n"
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTERO
    test:
    - ref: wait
    workflow: firewatch-ipi-aws
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: test-jws
