base_images:
  ansible:
    name: "4.12"
    namespace: ocp
    tag: ansible
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.12"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: az-test-interop-aws
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      ZONES_COUNT: "4"
    post:
    - ref: gather-aws-console
    - chain: ipi-deprovision
    pre:
    - ref: ipi-conf
    - ref: ipi-conf-telemetry
    - ref: ipi-conf-aws-custom-az
    - ref: ipi-conf-aws
    - ref: ipi-install-monitoringpvc
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: test-az-4.13
