base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: debug
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    pre:
    - chain: acm-install
zz_generated_metadata:
  branch: main_debug
  org: rhpit
  repo: interop-tests
