base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  upi-installer:
    name: "4.14"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: web-terminal-aws-rosa-hypershift-414
  cron: 0 10 25 12 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      CHANNEL_GROUP: candidate
      OPENSHIFT_VERSION: "4.14"
      REGION: us-west-2
    test:
    - ref: cucushift-hypershift-extended-health-check
    workflow: rosa-aws-sts-hypershift
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: web-terminal-hypershift-4.14-lp-rosa-hypershift
