base_images:
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: aws-rosa-hypershift-lp-interop-poc
  cron: 0 6 * * 1
  remote_api: true
  steps:
    cluster_profile: aws-cspi-qe
    env:
      FIREWATCH_CONFIG: |
        [
          {"step": "aws-*", "failure_type": "all", "classification": "Infrastructure AWS", "jira_project": "LPTOCPCI"},
          {"step": "gather-*", "failure_type": "all", "classification": "Other", "jira_project": "LPTOCPCI"},
          {"step": "osd-*", "failure_type": "all", "classification": "User Setup", "jira_project": "LPTOCPCI"},
          {"step": "rosa-", "failure_type": "all", "classification":  "Cluster Creation", "jira_project": "LPTOCPCI"}
        ]
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPTOCPCI
      FIREWATCH_JIRA_SERVER: https://issues.redhat.com
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.13"
      OPERATORS: |
        [
            {"name": "elasticsearch-operator", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators-redhat", "operator_group": "elasticsearch-operator-group"},
            {"name": "jaeger-product", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-distributed-tracing", "operator_group": "jaeger-operator-group"},
            {"name": "serverless-operator", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-serverless", "operator_group": "serverless-operator-group"},
            {"name": "mtc-operator", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-migration", "operator_group": "mtc-operator-group", "target_namespaces": "openshift-migration"},
            {"name": "kiali-ossm", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators"},
            {"name": "openshift-pipelines-operator-rh", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators"},
            {"name": "servicemeshoperator", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators"},
            {"name": "rh-service-binding-operator", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators"},
            {"name": "web-terminal", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators"}
        ]
      REGION: us-west-2
      ROSA_LOGIN_ENV: staging
    test:
    - ref: install-operators
    - ref: cucushift-hypershift-extended-health-check
    workflow: firewatch-rosa-aws-sts-hypershift
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: hypershift-poc-4.13
