base_images:
  application-ui-tests:
    name: "2.5"
    namespace: stolostron
    tag: application-ui-tests
  cli:
    name: "4.11"
    namespace: ocp
    tag: cli
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-aws
  interval: 960h
  steps:
    cluster_profile: aws-cspi-qe
    test:
    - ref: acm-tests-clc
zz_generated_metadata:
  branch: vboulos-containerize-config-fetch-cluster-jobs
  org: ascerra
  repo: acmqe-autotest
  variant: clone-rehearse
