base_images:
  cli:
    name: "4.11"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- context_dir: .
  dockerfile_path: ci/containerimages/install-operators/Dockerfile
  from: src
  to: acm-test
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-aws
  interval: 960h
  steps:
    cluster_profile: aws-cspi-qe
    test:
    - ref: acm-tests-clc
zz_generated_metadata:
  branch: vboulos-containerize-config-fetch-cluster-jobs
  org: ascerra
  repo: acmqe-autotest
  variant: clone-rehearse
