base_images:
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cspi-qe-slack-poc-pass-debug
  cron: 0 1 * * *
  steps:
    test:
    - as: report-passing
      commands: |
        echo "dummy passing test"
      from: cli
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
- as: cspi-qe-slack-poc-fail-debug
  cron: 0 1 * * *
  steps:
    test:
    - as: report-faling
      commands: |
        echo "dummy failing test"
        exit 1
      from: cli
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
