base_images:
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
images:
- dockerfile_path: Dockerfile.interops
  to: clc-ui-e2e
promotion:
  name: "1.0"
  namespace: acm-qe
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: main
  org: ascerra
  repo: clc-ui-e2e
