base_images:
  ansible:
    name: "4.12"
    namespace: ocp
    tag: ansible
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- context_dir: .
  dockerfile_path: interop_tests/dockerfiles/Dockerfile
  to: product-install
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: acm-install-rehearse-aws
  interval: 960h
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
    test:
    - chain: acm-interop-scenario
    workflow: cucushift-installer-rehearse-aws-ipi
zz_generated_metadata:
  branch: main
  org: ascerra
  repo: interop-tests
  variant: acm-install-rehearse-4.12
