base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  ocs-ci-tests:
    name: ocs-ci-container
    namespace: ci
    tag: stable
  upi-installer:
    name: "4.14"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
images:
- context_dir: .
  dockerfile_path: builder/Dockerfile
  to: cnv-tests
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cnv-tests-aws-upi-ocp414
  cron: 0 6 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      ODF_OPERATOR_CHANNEL: stable-4.14
      WORKER_INSTANCE_TYPE: c5n.metal
    test:
    - ref: interop-tests-deploy-cnv
    - ref: interop-tests-deploy-odf
    - chain: cucushift-installer-check-cluster-health
    - ref: interop-tests-cnv-tests-smoke
    workflow: cucushift-installer-rehearse-aws-upi
zz_generated_metadata:
  branch: main
  org: RedHatQE
  repo: cnv-tests
  variant: ocp-cnv-4.14-lp-interop
