base_images:
  ansible:
    name: "4.12"
    namespace: ocp
    tag: ansible
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.12"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_path: dockerfiles/docker_rhel8/Dockerfile
  from: test
  to: windup_integration_test
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: mta-installer-rehearse-aws
  cron: 0 8 * * 5
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
    test:
    - ref: mta-interop-tests-operator-test
    workflow: cucushift-installer-rehearse-aws-ipi
zz_generated_metadata:
  branch: main
  org: ascerra
  repo: windup_integration_test
  variant: installer-rehearse-4.12-mta-operator
